### ISSUE TITLE
read-csv example: automatic inference - intended behaviour?

### ISSUE THREAD

**Issue by hoffmannmic** [SINTEF/dlite#100] opened 2021-05-28 13:37 UTC
When automatic inference is switched on and a meta data file exist it wil be used.

Example:
`csv = dlite.Instance(f'csv:{csvfile}?' 'mode=r;' 'infer=False;' 'meta=http://meta.ifam.fraunhofer.de/0.1/Geyser')`

if infer=False and the meta-file exists (Geyser.json), it will be used and nice meta data are printed via `csv.meta`.

if infer=True and the meta-file does not exist, the automatic inference will produce some meta data.

if infer=True and the meta-file does exist, it will be used and automatic inference is ignored.

Also the strange entry in "iri" only occurs when automatic inference is used.

**Comment by jesper-friis** [comment] 2021-05-31 05:46
Good points. Entities are unique, so we have to call get_instance() to check if the entity already exists in memory. The problem is that get_instance() not only checks if the entity already is loaded to memory, but also transparently checks if it exists in any storage in the storage plugin path. 

I think the right solution is to add an option to get_instance() that allows us to turn off the transparent checking of storages when infer=True. 

The strange iri is corrected in PR #101

**Comment by jesper-friis** [comment] 2021-05-31 06:37
Hmm, I start to get second thoughts. All metadata are unique and immutable. If we have defined a metadata with a given uri in one place (even if it is a storage we haven't yet loaded), it will lead to confusion and contradictions if we allow to redefine it by automatic inference.

Maybe the current behaviour is actually not too bad, although a warning or error should probably be raised if an existing definition is used when infer=True.

**Comment by jesper-friis** [comment] 2021-06-01 09:21
After discussing with Thomas, I think the right solution is what is listed in issue #105

**Comment by jesper-friis** [comment] 2021-06-27 07:21
Closing - should be fixed in PR #107

**Closed by jesper-friis** 2021-06-27 07:21 UTC
